### PR TITLE
Can now access commands through separate files, added cmd_game command

### PR DESCRIPTION
**Pull request by TooManyJohns**
https://discordjs.guide/command-handling/#individual-command-files
^ Proper documentation on the subject

TD;LR
- Created /cmds folder to store command .js files
- modules.exports is how we will be exporting data in Node.js (so we can require() em)
-  We can access the client messaging through message.client , taking it in an executable form
ex: execute(message,args)
execute (message , mc)
can now dictate based upon args[0] being mc to operate the mc if, if it is 7days for example, it'd execute that instead (Check my MAL implementation , takes this to an entirely diff level)
- We use fs (Node's native file system module)
- We use Collection extending Map's functionality.

pretty straight forward, lets kick-butt on our PR's now in an organized fashion, 👍

### CODE REVIEW

**Comment by andrewandrepowell** [comment]
Please see my commit. We can probably automate the running of the commands further by simply looping through the available commands instead of switch/else-if.

**Comment by TooManyJohns** [comment]
Can you be a bit more specific in terms of looping, ? I do agree about automating the messaging I thought we discussed that last night was a good idea - but maybe we didn't.

 if (!msg.content.startsWith(vanillaPrefix) || msg.author.bot) return;
are you referring to change this to a while loop?

**Comment by andrewandrepowell** [comment]
Something like the following psuedo-code:

```
for (let cmdObj of cmdObjArray) {
  if (recvCmd==cmdObj.cmd) {
    cmdObj.execute(args);
  }
}
```

**Comment by TooManyJohns** [comment]
i dont think that benefits the bot removing the condition set beforehand that triggers a return if the prefix isn't entered, why go through the loop if you aren't using !vb? i also would argue again'st using if's inside a for loop, a switch case would be more efficient, and at the point i feel like it would be the best way to use the for loops inside the switch case implementation I was talking about with the index, thoughts?

**Comment by andrewandrepowell** [comment]
Looks good, and everything appears to still work.

**Pull request merged**
